In [1]:
import tensorflow as tf
print(tf.__version__)

2024-07-13 19:05:29.210958: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-13 19:05:29.211337: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-13 19:05:29.213657: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-13 19:05:29.220379: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-13 19:05:29.231346: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been 

2.17.0


In [3]:
mnist  = tf.keras.datasets.mnist

In [7]:
(x_train, y_train), (x_test,y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [11]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [15]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.39649343, -0.04050818,  0.02511239, -0.1336019 ,  1.0213941 ,
         0.09793656, -0.1362605 , -0.64592177,  0.3677367 ,  0.6035769 ]],
      dtype=float32)

In [16]:
tf.nn.softmax(predictions).numpy()

array([[0.05567022, 0.07947406, 0.08486411, 0.07240946, 0.2298284 ,
        0.09127486, 0.0722172 , 0.0433808 , 0.11954293, 0.15133801]],
      dtype=float32)

In [18]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [20]:
loss_fn(y_train[:1], predictions).numpy()

2.39388

In [21]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [24]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9875 - loss: 0.0387
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9886 - loss: 0.0336
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9888 - loss: 0.0328
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9895 - loss: 0.0319
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9911 - loss: 0.0262


In [25]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 1ms/step - accuracy: 0.9803 - loss: 0.0757


[0.07571224123239517, 0.9803000092506409]

In [26]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [27]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.58183120e-08, 3.17618050e-11, 2.13694200e-08, 4.69546109e-07,
        2.92848123e-14, 1.44743391e-08, 6.06807496e-18, 9.99999523e-01,
        2.58793237e-10, 4.18618811e-08],
       [1.36472734e-11, 4.92452784e-07, 9.99999404e-01, 5.28578425e-08,
        3.62968471e-23, 5.02097752e-10, 1.80422287e-14, 7.99574129e-25,
        4.21328597e-12, 3.89934839e-21],
       [3.63912539e-10, 9.99809682e-01, 9.99531112e-05, 2.11644220e-07,
        1.41330756e-05, 2.08457287e-08, 8.47175698e-08, 5.03432420e-05,
        2.55861505e-05, 1.83485727e-11],
       [9.99999166e-01, 1.06081715e-11, 3.72380238e-09, 1.04201619e-12,
        1.82135990e-12, 8.18851031e-09, 1.39843630e-08, 3.32291599e-08,
        2.71416251e-10, 8.05524223e-07],
       [1.35507594e-09, 1.10967076e-15, 1.82804420e-08, 3.45957594e-12,
        9.99007046e-01, 6.29916050e-11, 4.13091117e-10, 2.35234256e-06,
        1.16415960e-10, 9.90677974e-04]], dtype=float32)>